### ISSUE TITLE
Problem during make install: failed to create symbolic link '/usr/lib/x86_64-linux-gnu/libclang.so': File exists

### ISSUE THREAD

**Issue by Tylersuard** [purushottamkar/macer#3]
ln -s /usr/lib/x86_64-linux-gnu/libclang-*.so.1 /usr/lib/x86_64-linux-gnu/libclang.so

Error

ln: failed to create symbolic link '/usr/lib/x86_64-linux-gnu/libclang.so': File exists

Ubuntu 16, Anaconda with Python 3.6

**Comment by umairzahmed** [comment]
Thank you for pointing this out Tyler. This has been fixed in the latest commit.

**Comment by Tylersuard** [comment]
Thank you!
